name: "Update Changelog"

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update Changelog
        run: |
          echo "      ## 1.1.0 - 2023-25-07" >> CHANGELOG.md
          echo "      - add 'toStones'" >> CHANGELOG.md
          echo "## 1.0.0 - 2023-25-07" >> CHANGELOG.md
          echo "-initial release" >> CHANGELOG.md

      - name: Commit updated CHANGELOG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG"
          git push
